language: ruby
rvm:
	- "2.2.3"
addons:
	postgresql: "9.3"
services:
	- postgresql
before_script:
	- psql -c 'create database workshops_test;' -U postgres
	- cp config/database.yml.travis config/database.yml
install:
	- bundle install
